CREATE TABLE Semester (
    SID INT PRIMARY KEY,
    Bez VARCHAR(255) NOT NULL,
    Beginn DATE NOT NULL,
    Ende DATE NOT NULL,
    VLBeginn DATE NOT NULL,
    VLEnde DATE NOT NULL
);

CREATE TABLE Modulart (
    MAID INT PRIMARY KEY,
    Bez VARCHAR(255) NOT NULL,
    Aktiv BOOLEAN NOT NULL,
    LfdNr INT NOT NULL
);

CREATE TABLE Modul (
    MID INT PRIMARY KEY,
    Bez VARCHAR(255) NOT NULL,
    CP INT NOT NULL,
    Regelsemester INT NOT NULL,
    MAID INT NOT NULL,
    FOREIGN KEY (MAID) REFERENCES Modulart(MAID)
);

CREATE TABLE ModulBTArt (
    MBAID INT PRIMARY KEY,
    Bez VARCHAR(255) NOT NULL,
    Aktiv BOOLEAN NOT NULL,
    LfdNr INT NOT NULL
);

CREATE TABLE ModulBT (
    MBTID INT PRIMARY KEY,
    SWS INT,
    MID INT NOT NULL,
    MBAID INT NOT NULL,
    FOREIGN KEY (MID) REFERENCES Modul(MID),
    FOREIGN KEY (MBAID) REFERENCES ModulBTArt(MBAID)
);


CREATE TABLE Kurs (
    KID INT PRIMARY KEY,
    SID INT NOT NULL,
    MID INT NOT NULL,
    FOREIGN KEY (SID) REFERENCES Semester(SID),
    FOREIGN KEY (MID) REFERENCES Modul(MID)
);

CREATE TABLE Raum (
    RID INT PRIMARY KEY,
    RaumNr VARCHAR(255) NOT NULL
);

CREATE TABLE Terminart (
    TAID INT PRIMARY KEY,
    Bez VARCHAR(255) NOT NULL
);

CREATE TABLE Termin (
    TID INT PRIMARY KEY,
    TAID INT NOT NULL,
    FOREIGN KEY (TAID) REFERENCES Terminart(TAID)
);

CREATE TABLE Einzeltermin (
    ETID INT PRIMARY KEY,
    TID INT NOT NULL,
    DatumUhrzeitVon DATE NOT NULL,
    DatumUhrzeitBis DATE NOT NULL,
    FOREIGN KEY (TID) REFERENCES Termin(TID)
);

CREATE TABLE Zeitblock (
    ZBID INT PRIMARY KEY,
    UhrzeitVon DATE NOT NULL,
    UhrzeitBis DATE NOT NULL
);

CREATE TABLE Tag (
    TAGID INT PRIMARY KEY,
    Bez VARCHAR(255) NOT NULL
);

CREATE TABLE Wochentermin (
    TID INT NOT NULL,
    ZBID INT NOT NULL,
    TAGID INT NOT NULL,
    FOREIGN KEY (TID) REFERENCES Termin(TID),
    FOREIGN KEY (ZBID) REFERENCES Zeitblock(ZBID),
    FOREIGN KEY (TAGID) REFERENCES Tag(TAGID)
);



CREATE TABLE Person (
    PID INT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
);

CREATE TABLE Rolle (
    RID INT PRIMARY KEY,
    Bez VARCHAR(255) NOT NULL
);

CREATE TABLE Personenrolle (
    PRID INT PRIMARY KEY,
    PID INT NOT NULL,
    RID INT NOT NULL,
    DatumBeginn DATE NOT NULL,
    DatumEnde DATE,
    FOREIGN KEY (PID) REFERENCES Person(PID),
    FOREIGN KEY (RID) REFERENCES Rolle(RID)
);

CREATE TABLE Lehrperson (
    LID INT PRIMARY KEY,
    PRID INT NOT NULL,
    Steuernummer VARCHAR(50) NOT NULL,
    FOREIGN KEY (PRID) REFERENCES Personenrolle(PRID)
);

CREATE TABLE KursBT (
    KBTID INT PRIMARY KEY,
    KID INT NOT NULL,
    MBTID INT NOT NULL,
    RID INT NOT NULL,
    TID INT NOT NULL,
    LID INT NOT NULL,
    FOREIGN KEY (KID) REFERENCES Kurs(KID),
    FOREIGN KEY (MBTID) REFERENCES ModulBT(MBTID),
    FOREIGN KEY (RID) REFERENCES Raum(RID),
    FOREIGN KEY (TID) REFERENCES Termin(TID),
    FOREIGN KEY (LID) REFERENCES Lehrperson(LID)
);


CREATE TABLE StudentIn (
    STUID INT PRIMARY KEY,
    PRID INT NOT NULL,
    MatrNr VARCHAR(50) NOT NULL,
    FOREIGN KEY (PRID) REFERENCES Personenrolle(PRID)
);

CREATE TABLE StudentInKurs (
    STUID INT NOT NULL,
    KBTID INT NOT NULL,
    FOREIGN KEY (STUID) REFERENCES StudentIn(STUID),
    FOREIGN KEY (KBTID) REFERENCES KursBT(KBTID)
);

CREATE TABLE Sonstige (
    PRID INT PRIMARY KEY,
    -- Additional attributes here
    FOREIGN KEY (PRID) REFERENCES Personenrolle(PRID)
);


